apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: romainverduci
    provider: github
    repository: rom45
  name: romainverduci-rom45
spec:
  description: Imported application for romainverduci/rom45
  httpCloneURL: https://github.com/romainverduci/rom45.git
  org: romainverduci
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: rom45
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/romainverduci/rom45.git
