apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: romainverduci
    provider: github
    repository: rom41
  name: romainverduci-rom41
spec:
  description: Imported application for romainverduci/rom41
  httpCloneURL: https://github.com/romainverduci/rom41.git
  org: romainverduci
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: rom41
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/romainverduci/rom41.git
