apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: romainverduci
    provider: github
    repository: rom55
  name: romainverduci-rom55
spec:
  description: Imported application for romainverduci/rom55
  httpCloneURL: https://github.com/romainverduci/rom55.git
  org: romainverduci
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: rom55
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/romainverduci/rom55.git
