apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: romainverduci
    provider: github
    repository: rom52
  name: romainverduci-rom52
spec:
  description: Imported application for romainverduci/rom52
  httpCloneURL: https://github.com/romainverduci/rom52.git
  org: romainverduci
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: rom52
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/romainverduci/rom52.git
