apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: romainverduci
    provider: github
    repository: rom57
  name: romainverduci-rom57
spec:
  description: Imported application for romainverduci/rom57
  httpCloneURL: https://github.com/romainverduci/rom57.git
  org: romainverduci
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: rom57
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/romainverduci/rom57.git
